version: '3.8'
services:
  app:
    build:
      context: .
      args:
        UBUNTU_LOCALE: en_US.UTF-8
        RUBY_VERSION: 3.0.1
        RAILS_VERSION: 6.0.3.4
        NODE_VERSION: 15.3.0
        YARN_VERSION: 1.22.5
    working_dir: /home/uor/UoR
    volumes:
      - .:/home/uor/UoR
      - rvm:/home/uor/.rvm
      - nvm:/home/uor/.nvm
    ports:
      - 3000:3000
    environment:
      BINDING: 0.0.0.0
    tty: true
    # command: |
    #   bash -lc '
    #     rvm -v
    #     echo "nvm: `nvm -v`"
    #     irb
    #   '
volumes:
  rvm:
  nvm:

# docker build -t juniormesquitadandao/ubuntu-on-rails:20.04 -f Dockerfile.build .
# docker run --rm -it juniormesquitadandao/ubuntu-on-rails:20.04 bash
# docker-compose build
